---
title: "Rafael Uchoa de Lima's CV"
author: Rafael Uchoa de Lima
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/15aOO39_vOi8vevzUAUXEtjWYZVblN5fsWOkbcM3NEYw",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  # cat("View this CV online with links at _nickstrayer.me/datadrivencv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download PDF](https://github.com/nstrayer/cv/raw/master/strayer_cv.pdf)")
}
```

Contato {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



Habilidades Técnicas {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown) and [**datadrivencv**](https://github.com/nstrayer/datadrivencv).

Source code available on <i class="fa fa-github"></i>  [GitHub](https://github.com/RafaelUL/resume).

Last updated on `r Sys.Date()`.



Main
================================================================================

Rafael Uchoa de Lima {#title}
--------------------------------------------------------------------------------


Formação {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Experiência Profissional {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('professional_experience')
```



Cursos Complementares {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('courses')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

```{r}
CV %<>% print_links()
```

